### ISSUE TITLE
Third party libs example

### ISSUE THREAD

**Issue by makenova** [rstacruz/rsjs#1]
Hi,
  unlike the `.js-select2` [example](https://github.com/rstacruz/rsjs/blob/master/README.md#third-party-libraries), it is not clear how the `wow.js` function is scoped to affect only the `.wow` class.
Please, can you explain?
Thank you.

**Comment by rstacruz** [comment]
according to the wow.js [readme file](https://github.com/matthieua/WOW/blob/master/README.md), it defaults to using `.wow`.

**Comment by makenova** [comment]
Cool. It's not clear that [wow](https://github.com/matthieua/WOW) is an actual library, and not just an example. A link in or around the example would clear that up.
Thanks!
