### ISSUE TITLE
Your RSCSS link goes to an SEO spam farm

### ISSUE THREAD

**Issue by stevelandeyasana** [rstacruz/rsjs#11]
http://rscss.io/:

<img width="1259" alt="Screenshot 2023-04-20 at 10 26 28 AM" src="https://user-images.githubusercontent.com/38225497/233442442-2821c502-cffc-407d-af70-9313d16f361e.png">

I believe you meant: https://ricostacruz.com/rscss/

**Comment by rstacruz** [comment]
Thanks for the heads up, this is now fixed!
